# Generated by Django 5.0.1 on 2024-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='notemodel',
            name='image_str',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
